[package]
name = "lib3mf-converters"
version = "0.1.0"
edition = "2024"

[dependencies]
lib3mf-core = { path = "../lib3mf-core" }
thiserror = "2.0.18"
byteorder = "1.5.0"
glam = "0.31.0"

[dev-dependencies]
anyhow = "1.0"
