[package]
name = "lib3mf-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
lib3mf-core = { path = "../lib3mf-core" }

[dependencies.js-sys]
version = "0.3"
optional = true

[lib]
crate-type = ["cdylib", "rlib"]
